name: Linux Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:20.04  # Adjust the base image as necessary

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -qq -y wget unzip build-essential gcc-multilib g++-multilib libgcc1:i386

    - name: Run build
      working-directory: ./TraceFix
      run: make
    
    - name: Move release file to publish
      run: |
        # Make path
        mkdir -p publish/addons/tracefix/dlls

        # Move released file to dlls
        mv ./TraceFix/Release/tracefix_mm.so publish/addons/tracefix/dlls

        # Copy cstrike contents to publish dir
        cp -ar cstrike/. publish

    - name: Deploy artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tracefix-linux
        path: publish/*
