name: Linux Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Add i386 architecture
      run: sudo dpkg --add-architecture i386
      
    - name: Update repository
      run: sudo apt-get update

    - name: Install build dependencies
      run: sudo apt-get install -qq -y wget unzip build-essential gcc-multilib g++-multilib libgcc1 libgcc1:i386 libc6-dev libc6-dev-i386
    
    - name: Update alternatives
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10

    - name: Verify GCC version
      run: |
        gcc --version
        g++ --version

    - name: Run build
      working-directory: ./TraceFix
      run: make
    
    - name: Move release file to publish
      run: |
        # Make path
        mkdir -p publish/addons/tracefix/dlls

        # Move released file to dlls
        mv ./TraceFix/Release/tracefix_mm.so publish/addons/tracefix/dlls

        # Copy cstrike contents to publish dir
        cp -ar cstrike/. publish

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tracefix-linux
        path: publish/*
